const words = [
  {"word": "Alive", "antonyms": ["Unconscious", "Sluggish", "Deceased", "Dead"], "meaning": "Живой", "antonym": "Unconscious"},
  {"word": "Advance", "antonyms": ["Retire", "Behind", "Later", "Retreat"], "meaning": "Продвигаться", "antonym": "Retire"},
  {"word": "Admit", "antonyms": ["Repudiate", "Expel", "Oust", "Deny"], "meaning": "Признавать", "antonym": "Repudiate"},
{"word": "Agree", "antonyms": ["Reject", "Resist", "Object", "Disagree"], "meaning": null, "antonym": null},
  {"word": "Answer", "antonyms": ["Query", "Quiet", "Trouble", "Question"], "meaning": null, "antonym": null},
  {"word": "Absence", "antonyms": ["Plenty", "Existence", "Enough", "Presence"], "meaning": null, "antonym": null},
  {"word": "Abundant", "antonyms": ["Lacking", "Sparse", "Meager", "Scarce"], "meaning": "Plentiful, ample", "antonym": "Scarce"},
  {"word": "Accurate", "antonyms": ["Indefinite", "Unreliable", "Faulty", "Inaccurate"], "meaning": "Precise, correct", "antonym": "Inaccurate"},
  {"word": "Advantage", "antonyms": ["Harm", "Impotence", "Inferiority", "Disadvantage"], "meaning": null, "antonym": null},
  {"word": "Artificial", "antonyms": ["Genuine", "Real", "Unaffected", "Natural"], "meaning": null, "antonym": null},
  {"word": "Attack", "antonyms": ["Flight", "Shelter", "Shield", "Defense"], "meaning": null, "antonym": null},
  {"word": "Accept", "antonyms": ["Fail", "Deny", "Reject", "Refuse"], "meaning": "Acknowledge, receive", "antonym": "Reject"},
  {"word": "Ascend", "antonyms": ["Drop", "Slump", "Decline", "Descend"], "meaning": "Climb, rise", "antonym": "Descend"},
  {"word": "Attention", "antonyms": ["Disregard", "Lethargy", "Neglect", "Inattention"], "meaning": null, "antonym": null},
  {"word": "Approached", "antonyms": ["Departed", "Leave", "Retreat", "Receded"], "meaning": "Method, strategy", "antonym": "Avoid"},
  {"word": "Approval", "antonyms": ["Denial", "Veto", "Refusal", "Disapproval"], "meaning": null, "antonym": null},
  {"word": "Ancient", "antonyms": ["Current", "Fresh", "New", "Modern"], "meaning": "Old, antique", "antonym": "Modern"},
  {"word": "Asleep", "antonyms": ["Conscious", "Attentive", "Awake", "Awake"], "meaning": null, "antonym": null},
  {"word": "Ally", "antonyms": ["Antagonist", "Detractor", "Foe", "Enemy"], "meaning": "Associate, partner", "antonym": "Enemy"},
  {"word": "Bravery", "antonyms": ["Timidity", "Fear", "Cowardice", "Cowardice"], "meaning": "Courageous, fearless", "antonym": "Cowardly"},
  {"word": "Courteous", "antonyms": ["Rude", "Uncivil", "Unrefined", "Discourteous"], "meaning": "Courteous, well-mannered", "antonym": "Rude"},
  {"word": "Broad", "antonyms": ["Quiet", "Little", "Tiny", "Narrow"], "meaning": null, "antonym": null},
  {"word": "Blunt", "antonyms": ["Polite", "Subtle", "Sharp", "Sharp"], "meaning": null, "antonym": null},
  {"word": "Captivity", "antonyms": ["Liberty", "Freedom", "License", "Freedom"], "meaning": null, "antonym": null},
  {"word": "Correct", "antonyms": ["Improper", "Invalid", "Biased", "Incorrect"], "meaning": "Accurate, right", "antonym": "Incorrect"},
  {"word": "Cunning", "antonyms": ["Ignorant", "Blunt", "Rough", "Simple"], "meaning": null, "antonym": null},
  {"word": "Courage", "antonyms": ["Humility", "Timidity", "Irresolution", "Cowardice"], "meaning": "Brave, valiant", "antonym": "Timid"},
  {"word": "Calm", "antonyms": ["Harsh", "Furious", "Worried", "Troubled"], "meaning": null, "antonym": null},
  {"word": "Comfort", "antonyms": ["Gloom", "Injury", "Torment", "Discomfort"], "meaning": "Cozy, pleasant", "antonym": "Uncomfortable"},
  {"word": "Cruel", "antonyms": ["Gentle", "Compassionate", "Mild", "Kind"], "meaning": "Brutal, heartless", "antonym": "Kind"},
  {"word": "Borrow", "antonyms": ["Forfeit", "Lend", "Return", "Lend"], "meaning": "Loan, grant", "antonym": "Borrow"},
  {"word": "Clever", "antonyms": ["Foolish", "Ignorant", "Naive", "Stupid"], "meaning": null, "antonym": null},
  {"word": "Beginning", "antonyms": ["Finish", "Epilogue", "Finale", "Ending"], "meaning": "Commence, start", "antonym": "End"},
  {"word": "Cheap", "antonyms": ["Expensive", "Expensive", "Worthy", "Dear"], "meaning": "Inexpensive, affordable", "antonym": "Expensive"},
  {"word": "Beautiful", "antonyms": ["Drab", "Offensive", "Repulsive", "Ugly"], "meaning": "Attractive, lovely", "antonym": "Ugly"},
  {"word": "Conceal", "antonyms": ["Divulge", "Unwrap", "Ignore", "Reveal"], "meaning": null, "antonym": null},
  {"word": "Capable", "antonyms": ["Clumsy", "Stupid", "Ignorant", "Incapable"], "meaning": null, "antonym": null},
  {"word": "Careful", "antonyms": ["Careless", "Inexact", "Unwise", "Rush"], "meaning": "Careful, wary", "antonym": "Reckless"},
  {"word": "Bitter", "antonyms": ["Bland", "Pleasant", "Mild", "Sweet"], "meaning": "Sour, acrid", "antonym": "Sweet"},
  {"word": "Blame", "antonyms": ["Approval", "Peace", "Ratification", "Praise"], "meaning": null, "antonym": null},
  {"word": "Dainty", "antonyms": ["Ugly", "Inferior", "Coarse", "Clumsy"], "meaning": null, "antonym": null},
  {"word": "Frank", "antonyms": ["Timidity", "Shy", "Evasive", "Secretive"], "meaning": null, "antonym": null},
  {"word": "Feeble", "antonyms": ["Strong", "Powerful", "Expert", "Sturdy"], "meaning": null, "antonym": null},
  {"word": "Freedom", "antonyms": ["Slavery", "Inability", "Restraint", "Captivity"], "meaning": null, "antonym": null},
  {"word": "Foolish", "antonyms": ["Sane", "Realistic", "Serious", "Wise"], "meaning": null, "antonym": null},
  {"word": "Demand", "antonyms": ["Reply", "Offer", "Grant", "Supply"], "meaning": null, "antonym": null},
  {"word": "Famous", "antonyms": ["Obscure", "Inferior", "Typical", "Unknown"], "meaning": null, "antonym": null},
  {"word": "First", "antonyms": ["Minor", "Trivial", "Auxiliary", "Last"], "meaning": null, "antonym": null},
  {"word": "Friend", "antonyms": ["Foe", "Stranger", "Opponent", "Enemy"], "meaning": null, "antonym": null},
  {"word": "Ebb", "antonyms": ["Flow", "Incline", "Expansion", "Flow"], "meaning": null, "antonym": null},
  {"word": "Fortunate", "antonyms": ["Failing", "Lacking", "Losing", "Unfortunate"], "meaning": null, "antonym": null},
  {"word": "Decrease", "antonyms": ["Expansion", "Growth", "Enlargement", "Increase"], "meaning": null, "antonym": null},
  {"word": "Dark", "antonyms": ["Distinct", "Evident", "Vivacious", "Light"], "meaning": "Dim, obscure", "antonym": "Bright"},
  {"word": "Expand", "antonyms": ["Diminish", "Shrink", "Shrivel", "Contract"], "meaning": null, "antonym": null},
  {"word": "Entrance", "antonyms": ["Conclusion", "Egress", "Leave", "Exit"], "meaning": null, "antonym": null},
  {"word": "Despair", "antonyms": ["Cheer", "Faith", "Pleasure", "Hope"], "meaning": "Hopelessness, discouragement", "antonym": "Hope"},
  {"word": "Expensive", "antonyms": ["Cheap", "Worthless", "Reasonable", "Inexpensive"], "meaning": null, "antonym": null}
  {"word": "Frequent", "antonyms": ["Ceasing", "Irregular", "Rare", "Seldom"], "meaning": null, "antonym": null},
  {"word": "Dismal", "antonyms": ["Bright", "Intelligent", "Luminous", "Cheerful"], "meaning": null, "antonym": null},
  {"word": "End", "antonyms": ["Bottom", "Creation", "Origin", "Beginning"], "meaning": "Finish, conclude", "antonym": "Begin"},
  {"word": "Disappear", "antonyms": ["Begin", "Solidify", "Coagulate", "Appear"], "meaning": null, "antonym": null},
  {"word": "Fail", "antonyms": ["Ascend", "Rise", "Reach", "Succeed"], "meaning": "Flunk, falter", "antonym": "Succeed"},
  {"word": "Deep", "antonyms": ["Artless", "Flighty", "Trivial", "Shallow"], "meaning": null, "antonym": null},
  {"word": "Encourage", "antonyms": ["Agitate", "Sadden", "Dispirit", "Discourage"], "meaning": "Inspire, motivate", "antonym": "Discourage"},
  {"word": "Gentle", "antonyms": ["Surly", "Excited", "Harsh", "Rough"], "meaning": "Mild, tender", "antonym": "Harsh"},
  {"word": "Giant", "antonyms": ["Pygmy", "Dwarf", "Teeny", "Dwarf"], "meaning": null, "antonym": null},
  {"word": "Justice", "antonyms": ["Penalty", "Illegality", "Corruption", "Injustice"], "meaning": null, "antonym": null},
  {"word": "Interior", "antonyms": ["Outside", "Revealed", "Public", "Exterior"], "meaning": null, "antonym": null},
  {"word": "Happy", "antonyms": ["Miserable", "Serious", "Morose", "Sad"], "meaning": "Joyful, delighted", "antonym": "Sad"},
  {"word": "Immense", "antonyms": ["Minute", "Limited", "Restricted", "Tiny"], "meaning": null, "antonym": null},
  {"word": "Gloomy", "antonyms": ["Lively", "Luminous", "Intelligent", "Cheerful"], "meaning": null, "antonym": null},
  {"word": "Hate", "antonyms": ["Liking", "Sympathy", "Flattery", "Love"], "meaning": null, "antonym": null},
  {"word": "Intentional", "antonyms": ["Involuntary", "Unwilling", "Unplanned", "Accidental"], "meaning": null, "antonym": null},
  {"word": "Knowledge", "antonyms": ["Inanity", "Stupidity", "Impotence", "Ignorance"], "meaning": "Informed, educated", "antonym": "Ignorant"},
  {"word": "Healthy", "antonyms": ["Ill", "Diseased", "Infirm", "Unhealthy"], "meaning": "Fit, well", "antonym": "Sick"},
  {"word": "Hinder", "antonyms": ["Help", "Further", "Allow", "Aid"], "meaning": null, "antonym": null},
  {"word": "Hasten", "antonyms": ["Halt", "Hinder", "Dissuade", "Dawdle"], "meaning": null, "antonym": null},
  {"word": "Generous", "antonyms": ["Greedy", "Biased", "Prejudiced", "Mean"], "meaning": "Benevolent, charitable", "antonym": "Stingy"},
  {"word": "Interesting", "antonyms": ["Dull", "Repulsive", "Homely", "Uninteresting"], "meaning": null, "antonym": null},
  {"word": "Horizontal", "antonyms": ["Divergent", "Unfair", "Irregular", "Vertical"], "meaning": null, "antonym": null},
  {"word": "Hunger", "antonyms": ["Distaste", "Disgust", "Satiation", "Thirst"], "meaning": null, "antonym": null},
  {"word": "Honest", "antonyms": ["Counterfeit", "Deceitful", "Corrupt", "Dishonest"], "meaning": "Integrity, truthfulness", "antonym": "Dishonesty"},
  {"word": "Inferior", "antonyms": ["Chief", "Extraordinary", "Foremost", "Superior"], "meaning": "Lesser, subordinate", "antonym": "Superior"},
  {"word": "Imprison", "antonyms": ["Cease", "Permit", "Release", "Free"], "meaning": null, "antonym": null},
  {"word": "Humble", "antonyms": ["Brave", "Unrefined", "Intricate", "Proud"], "meaning": "Modest, meek", "antonym": "Arrogant"},
  {"word": "Harmful", "antonyms": ["Assisting", "Honest", "Fortunate", "Harmless"], "meaning": "Damaging, detrimental", "antonym": "Beneficial"},
  {"word": "Shallow", "antonyms": ["Superficial", "Lacking depth"], "meaning": "Superficial, lacking depth", "antonym": "Deep"},
  {"word": "Sharp", "antonyms": ["Pointed", "Keen"], "meaning": "Pointed, keen", "antonym": "Dull"},
  {"word": "Short", "antonyms": ["Brief", "Concise"], "meaning": "Brief, concise", "antonym": "Long"},
  {"word": "Shrink", "antonyms": ["Contract", "Reduce"], "meaning": "Contract, reduce", "antonym": "Expand"},
  {"word": "Shy", "antonyms": ["Timid", "Bashful"], "meaning": "Timid, bashful", "antonym": "Bold"},
  {"word": "Simple", "antonyms": ["Basic", "Uncomplicated"], "meaning": "Basic, uncomplicated", "antonym": "Complex"},
  {"word": "Sincere", "antonyms": ["Genuine", "Honest"], "meaning": "Genuine, honest", "antonym": "Insincere"},
  {"word": "Single", "antonyms": ["Solo", "Individual"], "meaning": "Solo, individual", "antonym": "Multiple"},
  {"word": "Smart", "antonyms": ["Intelligent", "Clever"], "meaning": "Intelligent, clever", "antonym": "Stupid"},
  {"word": "Smooth", "antonyms": ["Even", "Sleek"], "meaning": "Even, sleek", "antonym": "Rough"},
  {"word": "Soft", "antonyms": ["Gentle", "Tender"], "meaning": "Gentle, tender", "antonym": "Hard"},
  {"word": "Sour", "antonyms": ["Tart", "Acidic"], "meaning": "Tart, acidic", "antonym": "Sweet"},
  {"word": "Specific", "antonyms": ["Precise", "Particular"], "meaning": "Precise, particular", "antonym": "General"},
  {"word": "Start", "antonyms": ["Begin", "Commence"], "meaning": "Begin, commence", "antonym": "End"},
  {"word": "Stop", "antonyms": ["Halt", "Cease"], "meaning": "Halt, cease", "antonym": "Continue"},
  {"word": "Strong", "antonyms": ["Powerful", "Sturdy"], "meaning": "Powerful, sturdy", "antonym": "Weak"},
  {"word": "Success", "antonyms": ["Achievement", "Triumph"], "meaning": "Achievement, triumph", "antonym": "Failure"},
  {"word": "Succeed", "antonyms": ["Accomplish", "Achieve"], "meaning": "Accomplish, achieve", "antonym": "Fail"},
  {"word": "Superior", "antonyms": ["Better", "Higher"], "meaning": "Better, higher", "antonym": "Inferior"},
  {"word": "Support", "antonyms": ["Assist", "Aid"], "meaning": "Assist, aid", "antonym": "Oppose"},
  {"word": "Sweet", "antonyms": ["Sugary", "Pleasant"], "meaning": "Sugary, pleasant", "antonym": "Bitter"}
  {"word": "Tall", "antonyms": ["High", "Towering"], "meaning": "High, towering", "antonym": "Short"},
  {"word": "Terrible", "antonyms": ["Dreadful", "Horrible"], "meaning": "Dreadful, horrible", "antonym": "Wonderful"},
  {"word": "Thick", "antonyms": ["Dense", "Bulky"], "meaning": "Dense, bulky", "antonym": "Thin"},
  {"word": "Tight", "antonyms": ["Firm", "Secure"], "meaning": "Firm, secure", "antonym": "Loose"},
  {"word": "Together", "antonyms": ["United", "Connected"], "meaning": "United, connected", "antonym": "Apart"},
  {"word": "Tough", "antonyms": ["Strong", "Resilient"], "meaning": "Strong, resilient", "antonym": "Weak"},
  {"word": "Transparent", "antonyms": ["Clear", "See-through"], "meaning": "Clear, see-through", "antonym": "Opaque"},
  {"word": "True", "antonyms": ["Genuine", "Accurate"], "meaning": "Genuine, accurate", "antonym": "False"},
  {"word": "Trust", "antonyms": ["Confidence", "Reliance"], "meaning": "Confidence, reliance", "antonym": "Distrust"},
  {"word": "Ugly", "antonyms": ["Unattractive", "Hideous"], "meaning": "Unattractive, hideous", "antonym": "Beautiful"},
  {"word": "Unite", "antonyms": ["Join", "Connect"], "meaning": "Join, connect", "antonym": "Separate"},
  {"word": "Upset", "antonyms": ["Disturbed", "Agitated"], "meaning": "Disturbed, agitated", "antonym": "Calm"},
  {"word": "Useful", "antonyms": ["Beneficial", "Valuable"], "meaning": "Beneficial, valuable", "antonym": "Useless"},
  {"word": "Vacant", "antonyms": ["Empty", "Unoccupied"], "meaning": "Empty, unoccupied", "antonym": "Occupied"},
  {"word": "Valuable", "antonyms": ["Precious", "Priceless"], "meaning": "Precious, priceless", "antonym": "Worthless"},
  {"word": "Vast", "antonyms": ["Enormous", "Immense"], "meaning": "Enormous, immense", "antonym": "Limited"},
  {"word": "Victory", "antonyms": ["Triumph", "Success"], "meaning": "Triumph, success", "antonym": "Defeat"},
  {"word": "Visible", "antonyms": ["Observable", "Apparent"], "meaning": "Observable, apparent", "antonym": "Invisible"},
  {"word": "Vital", "antonyms": ["Essential", "Crucial"], "meaning": "Essential, crucial", "antonym": "Insignificant"},
  {"word": "Volunteer", "antonyms": ["Offer", "Enlist"], "meaning": "Offer, enlist", "antonym": "Compulsory"},
  {"word": "Weak", "antonyms": ["Frail", "Feeble"], "meaning": "Frail, feeble", "antonym": "Strong"},
  {"word": "Wealthy", "antonyms": ["Rich", "Affluent"], "meaning": "Rich, affluent", "antonym": "Poor"},
  {"word": "Whole", "antonyms": ["Entire", "Complete"], "meaning": "Entire, complete", "antonym": "Part"},
  {"word": "Wise", "antonyms": ["Intelligent", "Knowledgeable"], "meaning": "Intelligent, knowledgeable", "antonym": "Foolish"},
  {"word": "Withdraw", "antonyms": ["Retract", "Remove"], "meaning": "Retract, remove", "antonym": "Deposit"},
  {"word": "Wonderful", "antonyms": ["Marvelous", "Fantastic"], "meaning": "Marvelous, fantastic", "antonym": "Terrible"},
  {"word": "Worry", "antonyms": ["Anxious", "Concern"], "meaning": "Anxious, concern", "antonym": "Relax"},
  {"word": "Worthless", "antonyms": ["Valueless", "Insignificant"], "meaning": "Valueless, insignificant", "antonym": "Valuable"},
  {"word": "Wrong", "antonyms": ["Incorrect", "Mistaken"], "meaning": "Incorrect, mistaken", "antonym": "Right"},
  {"word": "Yield", "antonyms": ["Surrender", "Concede"], "meaning": "Surrender, concede", "antonym": "Resist"},
  {"word": "Young", "antonyms": ["Youthful", "Juvenile"], "meaning": "Youthful, juvenile", "antonym": "Old"},
  {"word": "Zenith", "antonyms": ["Peak", "Apex"], "meaning": "Peak, apex", "antonym": "Nadir"}
  {"word": "Abundant", "antonyms": ["Lacking", "Sparse", "Meager", "Scarce"], "meaning": "Plentiful, ample", "antonym": "Scarce"},
  {"word": "Accept", "antonyms": ["Fail", "Deny", "Reject", "Refuse"], "meaning": "Acknowledge, receive", "antonym": "Reject"},
  {"word": "Accurate", "antonyms": ["Indefinite", "Unreliable", "Faulty", "Inaccurate"], "meaning": "Precise, correct", "antonym": "Inaccurate"},
  {"word": "Active", "antonyms": ["Energetic", "Engaged"], "meaning": "Energetic, engaged", "antonym": "Inactive"},
  {"word": "Add", "antonyms": ["Include", "Append"], "meaning": "Include, append", "antonym": "Subtract"},
  {"word": "Advance", "antonyms": ["Progress", "Improvement"], "meaning": "Progress, improvement", "antonym": "Retreat"},
  {"word": "Agree", "antonyms": ["Consent", "Concur"], "meaning": "Consent, concur", "antonym": "Disagree"},
  {"word": "Aid", "antonyms": ["Assist", "Help"], "meaning": "Assist, help", "antonym": "Hinder"},
  {"word": "Alert", "antonyms": ["Vigilant", "Attentive"], "meaning": "Vigilant, attentive", "antonym": "Drowsy"},
  {"word": "Ally", "antonyms": ["Associate", "Partner"], "meaning": "Associate, partner", "antonym": "Enemy"},
  {"word": "Ancient", "antonyms": ["Old", "Antique"], "meaning": "Old, antique", "antonym": "Modern"},
  {"word": "Answer", "antonyms": ["Respond", "Reply"], "meaning": "Respond, reply", "antonym": "Question"},
  {"word": "Apparent", "antonyms": ["Obvious", "Clear"], "meaning": "Obvious, clear", "antonym": "Hidden"},
  {"word": "Approach", "antonyms": ["Method", "Strategy"], "meaning": "Method, strategy", "antonym": "Avoid"},
  {"word": "Arrogant", "antonyms": ["Proud", "Haughty"], "meaning": "Proud, haughty", "antonym": "Humble"},
  {"word": "Ascend", "antonyms": ["Climb", "Rise"], "meaning": "Climb, rise", "antonym": "Descend"},
  {"word": "Attack", "antonyms": ["Assault", "Strike"], "meaning": "Assault, strike", "antonym": "Defend"},
  {"word": "Authentic", "antonyms": ["Genuine", "Real"], "meaning": "Genuine, real", "antonym": "Fake"},
  {"word": "Awful", "antonyms": ["Terrible", "Dreadful"], "meaning": "Terrible, dreadful", "antonym": "Wonderful"},
  {"word": "Balance", "antonyms": ["Equilibrium", "Stability"], "meaning": "Equilibrium, stability", "antonym": "Imbalance"},
  {"word": "Beautiful", "antonyms": ["Attractive", "Lovely"], "meaning": "Attractive, lovely", "antonym": "Ugly"},
  {"word": "Begin", "antonyms": ["Commence", "Start"], "meaning": "Commence, start", "antonym": "End"},
  {"word": "Benevolent", "antonyms": ["Kind", "Generous"], "meaning": "Kind, generous", "antonym": "Malevolent"},
  {"word": "Best", "antonyms": ["Finest", "Superior"], "meaning": "Finest, superior", "antonym": "Worst"},
  {"word": "Bitter", "antonyms": ["Sour", "Acrid"], "meaning": "Sour, acrid", "antonym": "Sweet"},
  {"word": "Brave", "antonyms": ["Courageous", "Fearless"], "meaning": "Courageous, fearless", "antonym": "Cowardly"},
  {"word": "Bright", "antonyms": ["Radiant", "Vivid"], "meaning": "Radiant, vivid", "antonym": "Dull"},
  {"word": "Cautious", "antonyms": ["Careful", "Wary"], "meaning": "Careful, wary", "antonym": "Reckless"},
  {"word": "Certain", "antonyms": ["Confident", "Definite"], "meaning": "Confident, definite", "antonym": "Doubtful"},
  {"word": "Challenge", "antonyms": ["Test", "Dare"], "meaning": "Test, dare", "antonym": "Support"},
  {"word": "Charming", "antonyms": ["Delightful", "Captivating"], "meaning": "Delightful, captivating", "antonym": "Repulsive"},
  {"word": "Cheap", "antonyms": ["Inexpensive", "Affordable"], "meaning": "Inexpensive, affordable", "antonym": "Expensive"},
  {"word": "Cheerful", "antonyms": ["Happy", "Joyful"], "meaning": "Happy, joyful", "antonym": "Sad"},
  {"word": "Clear", "antonyms": ["Transparent", "Obvious"], "meaning": "Transparent, obvious", "antonym": "Unclear"},
  {"word": "Close", "antonyms": ["Near", "Adjacent"], "meaning": "Near, adjacent", "antonym": "Distant"},
  {"word": "Comfortable", "antonyms": ["Cozy", "Pleasant"], "meaning": "Cozy, pleasant", "antonym": "Uncomfortable"},
  {"word": "Common", "antonyms": ["Ordinary", "Typical"], "meaning": "Ordinary, typical", "antonym": "Rare"},
  {"word": "Complete", "antonyms": ["Whole", "Entire"], "meaning": "Whole, entire", "antonym": "Incomplete"},
  {"word": "Complex", "antonyms": ["Complicated", "Intricate"], "meaning": "Complicated, intricate", "antonym": "Simple"},
  {"word": "Confident", "antonyms": ["Assured", "Self-assured"], "meaning": "Assured, self-assured", "antonym": "Insecure"},
  {"word": "Confuse", "antonyms": ["Baffle", "Puzzle"], "meaning": "Baffle, puzzle", "antonym": "Clarify"},
  {"word": "Consider", "antonyms": ["Contemplate", "Ponder"], "meaning": "Contemplate, ponder", "antonym": "Disregard"},
  {"word": "Constructive", "antonyms": ["Positive", "Helpful"], "meaning": "Positive, helpful", "antonym": "Destructive"},
  {"word": "Correct", "antonyms": ["Accurate", "Right"], "meaning": "Accurate, right", "antonym": "Incorrect"},
  {"word": "Courageous", "antonyms": ["Brave", "Valiant"], "meaning": "Brave, valiant", "antonym": "Timid"},
  {"word": "Create", "antonyms": ["Generate", "Produce"], "meaning": "Generate, produce", "antonym": "Destroy"},
  {"word": "Cruel", "antonyms": ["Brutal", "Heartless"], "meaning": "Brutal, heartless", "antonym": "Kind"},
  {"word": "Curious", "antonyms": ["Inquisitive", "Eager"], "meaning": "Inquisitive, eager", "antonym": "Indifferent"},
  {"word": "Dangerous", "antonyms": ["Hazardous", "Risky"], "meaning": "Hazardous, risky", "antonym": "Safe"},
  {"word": "Dark", "antonyms": ["Dim", "Obscure"], "meaning": "Dim, obscure", "antonym": "Bright"},
  {"word": "Defend", "antonyms": ["Protect", "Guard"], "meaning": "Protect, guard", "antonym": "Attack"},
  {"word": "Delay", "antonyms": ["Postpone", "Defer"], "meaning": "Postpone, defer", "antonym": "Expedite"},
  {"word": "Depend", "antonyms": ["Rely", "Count on"], "meaning": "Rely, count on", "antonym": "Independent"},
  {"word": "Despair", "antonyms": ["Hopelessness", "Discouragement"], "meaning": "Hopelessness, discouragement", "antonym": "Hope"},
  {"word": "Destroy", "antonyms": ["Ruin", "Demolish"], "meaning": "Ruin, demolish", "antonym": "Build"},
  {"word": "Different", "antonyms": ["Diverse", "Distinct"], "meaning": "Diverse, distinct", "antonym": "Similar"},
  {"word": "Difficult", "antonyms": ["Challenging", "Hard"], "meaning": "Challenging, hard", "antonym": "Easy"},
  {"word": "Diminish", "antonyms": ["Reduce", "Decrease"], "meaning": "Reduce, decrease", "antonym": "Increase"},
  {"word": "Dirty", "antonyms": ["Filthy", "Unclean"], "meaning": "Filthy, unclean", "antonym": "Clean"},
  {"word": "Discover", "antonyms": ["Uncover", "Find"], "meaning": "Uncover, find", "antonym": "Lose"}
  {"word": "Dull", "antonyms": ["Boring", "Tedious"], "meaning": "Boring, tedious", "antonym": "Interesting"},
  {"word": "Educated", "antonyms": ["Knowledgeable", "Learned"], "meaning": "Knowledgeable, learned", "antonym": "Ignorant"},
  {"word": "Efficient", "antonyms": ["Effective", "Productive"], "meaning": "Effective, productive", "antonym": "Inefficient"},
  {"word": "Encourage", "antonyms": ["Inspire", "Motivate"], "meaning": "Inspire, motivate", "antonym": "Discourage"},
  {"word": "End", "antonyms": ["Finish", "Conclude"], "meaning": "Finish, conclude", "antonym": "Begin"},
  {"word": "Enjoy", "antonyms": ["Appreciate", "Relish"], "meaning": "Appreciate, relish", "antonym": "Detest"},
  {"word": "Equal", "antonyms": ["Equivalent", "Identical"], "meaning": "Equivalent, identical", "antonym": "Unequal"},
  {"word": "Evolve", "antonyms": ["Develop", "Progress"], "meaning": "Develop, progress", "antonym": "Regress"},
  {"word": "Excessive", "antonyms": ["Extreme", "Undue"], "meaning": "Extreme, undue", "antonym": "Moderate"},
  {"word": "Expand", "antonyms": ["Enlarge", "Extend"], "meaning": "Enlarge, extend", "antonym": "Contract"},
  {"word": "Explain", "antonyms": ["Elaborate", "Clarify"], "meaning": "Elaborate, clarify", "antonym": "Confuse"},
  {"word": "Fail", "antonyms": ["Flunk", "Falter"], "meaning": "Flunk, falter", "antonym": "Succeed"},
  {"word": "Fake", "antonyms": ["Faux", "Counterfeit"], "meaning": "Faux, counterfeit", "antonym": "Genuine"},
  {"word": "Familiar", "antonyms": ["Known", "Recognized"], "meaning": "Known, recognized", "antonym": "Strange"},
  {"word": "Fast", "antonyms": ["Quick", "Rapid"], "meaning": "Quick, rapid", "antonym": "Slow"},
  {"word": "Fearless", "antonyms": ["Bold", "Brave"], "meaning": "Bold, brave", "antonym": "Afraid"},
  {"word": "Final", "antonyms": ["Last", "Ultimate"], "meaning": "Last, ultimate", "antonym": "Initial"},
  {"word": "Flexible", "antonyms": ["Adaptable", "Pliable"], "meaning": "Adaptable, pliable", "antonym": "Inflexible"},
  {"word": "Forget", "antonyms": ["Neglect", "Overlook"], "meaning": "Neglect, overlook", "antonym": "Remember"},
  {"word": "Forward", "antonyms": ["Ahead", "Progressive"], "meaning": "Ahead, progressive", "antonym": "Backward"},
  {"word": "Fresh", "antonyms": ["New", "Recent"], "meaning": "New, recent", "antonym": "Stale"},
  {"word": "Friendly", "antonyms": ["Amicable", "Sociable"], "meaning": "Amicable, sociable", "antonym": "Hostile"},
  {"word": "Generous", "antonyms": ["Benevolent", "Charitable"], "meaning": "Benevolent, charitable", "antonym": "Stingy"},
  {"word": "Gentle", "antonyms": ["Mild", "Tender"], "meaning": "Mild, tender", "antonym": "Harsh"},
  {"word": "Genuine", "antonyms": ["Authentic", "Real"], "meaning": "Authentic, real", "antonym": "Fake"},
  {"word": "Gigantic", "antonyms": ["Enormous", "Colossal"], "meaning": "Enormous, colossal", "antonym": "Tiny"},
  {"word": "Glorious", "antonyms": ["Magnificent", "Splendid"], "meaning": "Magnificent, splendid", "antonym": "Miserable"},
  {"word": "Graceful", "antonyms": ["Elegant", "Refined"], "meaning": "Elegant, refined", "antonym": "Clumsy"},
  {"word": "Grow", "antonyms": ["Expand", "Develop"], "meaning": "Expand, develop", "antonym": "Shrink"},
  {"word": "Happy", "antonyms": ["Joyful", "Delighted"], "meaning": "Joyful, delighted", "antonym": "Sad"},
  {"word": "Harmful", "antonyms": ["Damaging", "Detrimental"], "meaning": "Damaging, detrimental", "antonym": "Beneficial"},
  {"word": "Harsh", "antonyms": ["Severe", "Stern"], "meaning": "Severe, stern", "antonym": "Gentle"},
  {"word": "Healthy", "antonyms": ["Fit", "Well"], "meaning": "Fit, well", "antonym": "Sick"},
  {"word": "Help", "antonyms": ["Aid", "Assist"], "meaning": "Aid, assist", "antonym": "Hinder"},
  {"word": "Hide", "antonyms": ["Conceal", "Camouflage"], "meaning": "Conceal, camouflage", "antonym": "Reveal"},
  {"word": "Honesty", "antonyms": ["Integrity", "Truthfulness"], "meaning": "Integrity, truthfulness", "antonym": "Dishonesty"},
  {"word": "Humble", "antonyms": ["Modest", "Meek"], "meaning": "Modest, meek", "antonym": "Arrogant"},
  {"word": "Ignorant", "antonyms": ["Unaware", "Uninformed"], "meaning": "Unaware, uninformed", "antonym": "Knowledgeable"},
  {"word": "Ill", "antonyms": ["Sick", "Unwell"], "meaning": "Sick, unwell", "antonym": "Healthy"},
  {"word": "Imaginary", "antonyms": ["Fictional", "Unreal"], "meaning": "Fictional, unreal", "antonym": "Real"},
  {"word": "Immediate", "antonyms": ["Instant", "Prompt"], "meaning": "Instant, prompt", "antonym": "Delayed"},
  {"word": "Impatient", "antonyms": ["Restless", "Eager"], "meaning": "Restless, eager", "antonym": "Patient"},
  {"word": "Increase", "antonyms": ["Expand", "Grow"], "meaning": "Expand, grow", "antonym": "Decrease"},
  {"word": "Independent", "antonyms": ["Self-reliant", "Autonomous"], "meaning": "Self-reliant, autonomous", "antonym": "Dependent"},
  {"word": "Inferior", "antonyms": ["Lesser", "Subordinate"], "meaning": "Lesser, subordinate", "antonym": "Superior"},
  {"word": "Innocent", "antonyms": ["Pure", "Guiltless"], "meaning": "Pure, guiltless", "antonym": "Guilty"},
  {"word": "Inside", "antonyms": ["Interior", "Internal"], "meaning": "Interior, internal", "antonym": "Outside"},
  {"word": "Intense", "antonyms": ["Fierce", "Strong"], "meaning": "Fierce, strong", "antonym": "Mild"},
  {"word": "Introduce", "antonyms": ["Present", "Acquaint"], "meaning": "Present, acquaint", "antonym": "Exclude"},
  {"word": "Join", "antonyms": ["Unite", "Connect"], "meaning": "Unite, connect", "antonym": "Separate"},
  {"word": "Joyful", "antonyms": ["Happy", "Elated"], "meaning": "Happy, elated", "antonym": "Gloomy"},
  {"word": "Jumbo", "antonyms": ["Giant", "Colossal"], "meaning": "Giant, colossal", "antonym": "Tiny"},
  {"word": "Knowledgeable", "antonyms": ["Informed", "Educated"], "meaning": "Informed, educated", "antonym": "Ignorant"},
  {"word": "Lament", "antonyms": ["Mourn", "Grieve"], "meaning": "Mourn, grieve", "antonym": "Rejoice"},
  {"word": "Lend", "antonyms": ["Loan", "Grant"], "meaning": "Loan, grant", "antonym": "Borrow"},
  {"word": "Liberated", "antonyms": ["Free", "Emancipated"], "meaning": "Free, emancipated", "antonym": "Enslaved"},
  {"word": "Light", "antonyms": ["Bright", "Illuminated"], "meaning": "Bright, illuminated", "antonym": "Dark"},
  {"word": "Limited", "antonyms": ["Restricted", "Finite"], "meaning": "Restricted, finite", "antonym": "Unlimited"},
  {"word": "Listen", "antonyms": ["Hear", "Pay attention"], "meaning": "Hear, pay attention", "antonym": "Ignore"},
  {"word": "Little", "antonyms": ["Small", "Tiny"], "meaning": "Small, tiny", "antonym": "Big"},
  {"word": "Long", "antonyms": ["Lengthy", "Extended"], "meaning": "Lengthy, extended", "antonym": "Short"},
  {"word": "Loud", "antonyms": ["Noisy", "Boisterous"], "meaning": "Noisy, boisterous", "antonym": "Quiet"},
  {"word": "Love", "antonyms": ["Adore", "Cherish"], "meaning": "Adore, cherish", "antonym": "Hate"},
  {"word": "Loyal", "antonyms": ["Faithful", "Dedicated"], "meaning": "Faithful, dedicated", "antonym": "Disloyal"},
  {"word": "Major", "antonyms": ["Significant", "Important"], "meaning": "Significant, important", "antonym": "Minor"},
  {"word": "Meek", "antonyms": ["Humble", "Mild"], "meaning": "Humble, mild", "antonym": "Bold"},
  {"word": "Messy", "antonyms": ["Untidy", "Disorganized"], "meaning": "Untidy, disorganized", "antonym": "Neat"},
  {"word": "Mighty", "antonyms": ["Powerful", "Strong"], "meaning": "Powerful, strong", "antonym": "Weak"},
  {"word": "Minor", "antonyms": ["Lesser", "Small"], "meaning": "Lesser, small", "antonym": "Major"},
  {"word": "Modest", "antonyms": ["Humble", "Unassuming"], "meaning": "Humble, unassuming", "antonym": "Arrogant"},
  {"word": "Monotonous", "antonyms": ["Dull", "Tedious"], "meaning": "Dull, tedious", "antonym": "Varied"},
  {"word": "Narrow", "antonyms": ["Thin", "Slender"], "meaning": "Thin, slender", "antonym": "Wide"},
  {"word": "Natural", "antonyms": ["Genuine", "Inherent"], "meaning": "Genuine, inherent", "antonym": "Artificial"},
  {"word": "Naughty", "antonyms": ["Mischievous", "Disobedient"], "meaning": "Mischievous, disobedient", "antonym": "Well-behaved"},
  {"word": "Neat", "antonyms": ["Tidy", "Organized"], "meaning": "Tidy, organized", "antonym": "Messy"},
  {"word": "Nervous", "antonyms": ["Anxious", "Apprehensive"], "meaning": "Anxious, apprehensive", "antonym": "Calm"},
  {"word": "Normal", "antonyms": ["Regular", "Typical"], "meaning": "Regular, typical", "antonym": "Abnormal"},
  {"word": "Obedient", "antonyms": ["Compliant", "Submissive"], "meaning": "Compliant, submissive", "antonym": "Defiant"},
  {"word": "Observe", "antonyms": ["Watch", "Notice"], "meaning": "Watch, notice", "antonym": "Ignore"},
  {"word": "Odd", "antonyms": ["Strange", "Peculiar"], "meaning": "Strange, peculiar", "antonym": "Even"},
  {"word": "Open", "antonyms": ["Unlocked", "Accessible"], "meaning": "Unlocked, accessible", "antonym": "Closed"},
  {"word": "Optimistic", "antonyms": ["Positive", "Hopeful"], "meaning": "Positive, hopeful", "antonym": "Pessimistic"},
  {"word": "Original", "antonyms": ["Authentic", "Genuine"], "meaning": "Authentic, genuine", "antonym": "Copy"},
  {"word": "Out", "antonyms": ["Exterior", "Outside"], "meaning": "Exterior, outside", "antonym": "In"},
  {"word": "Painful", "antonyms": ["Achy", "Agonizing"], "meaning": "Achy, agonizing", "antonym": "Painless"},
  {"word": "Patient", "antonyms": ["Tolerant", "Understanding"], "meaning": "Tolerant, understanding", "antonym": "Impatient"},
  {"word": "Peaceful", "antonyms": ["Serene", "Calm"], "meaning": "Serene, calm", "antonym": "Chaotic"},
  {"word": "Playful", "antonyms": ["Lively", "Frolicsome"], "meaning": "Lively, frolicsome", "antonym": "Serious"},
  {"word": "Pleasant", "antonyms": ["Enjoyable", "Pleasing"], "meaning": "Enjoyable, pleasing", "antonym": "Unpleasant"}
];

const wordList = document.getElementById('word-list');
const searchInput = document.getElementById('search');

displayWords(words);

searchInput.addEventListener('input', () => {
  const term = searchInput.value.toLowerCase();
  const filtered = words.filter(w => w.word.toLowerCase().includes(term));
  displayWords(filtered);
});

function displayWords(list) {
  wordList.innerHTML = '';
  list.forEach(w => {
    const li = document.createElement('li');
    li.className = 'word-item';
    li.innerHTML = `<strong>${w.word}</strong> — <span class="meaning">${w.meaning}</span>`;
    li.addEventListener('click', () => {
      const antonymsHTML = `<div class="antonyms">Антонимы: ${w.antonyms.join(', ')}</div>`;
      li.innerHTML = `<strong>${w.word}</strong> — <span class="meaning">${w.meaning}</span>${antonymsHTML}`;
    });
    wordList.appendChild(li);
  });
}
